#!/bin/bash
# =============================================================================
# Claude Kit - Git Hooks Setup
# =============================================================================
#
# Installs pre-commit hooks for template validation and manifest integrity.
#
# Usage:
#   ./scripts/setup-hooks.sh [METHOD]
#
# METHODS:
#   native        Native git hooks (no dependencies)
#   pre-commit    Pre-commit framework (requires: pip install pre-commit)
#   auto          Auto-detect (default)
#
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOKS_DIR="$PROJECT_ROOT/.git/hooks"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

# ============================================================================
# Configuration
# ============================================================================

METHOD="${1:-auto}"

show_help() {
    cat << EOF
🔧 Claude Kit - Git Hooks Setup

Installs pre-commit hooks for automated template validation.

Usage: $0 [METHOD]

METHODS:
  native        Native git hooks (no dependencies, lightweight)
  pre-commit    Pre-commit framework (industry standard, requires Python)
  auto          Auto-detect best method (default)

FEATURES:
  ✓ Template validation (ERROR → block commit)
  ✓ Manifest integrity check (hash verification)
  ✓ Version bump warning (not blocking)

EXAMPLES:
  $0              # Auto-detect
  $0 native       # Use native hooks
  $0 pre-commit   # Use pre-commit framework

EOF
}

if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]; then
    show_help
    exit 0
fi

# ============================================================================
# Pre-flight Checks
# ============================================================================

if [ ! -d "$PROJECT_ROOT/.git" ]; then
    echo -e "${RED}❌ Error: Not a git repository${NC}"
    echo "Run this script from the claude-kit project root"
    exit 1
fi

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           Claude Kit - Git Hooks Setup                       ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ============================================================================
# Method Selection
# ============================================================================

if [ "$METHOD" == "auto" ]; then
    echo -e "${BLUE}🔍 Auto-detecting best method...${NC}"

    if command -v pre-commit &> /dev/null; then
        METHOD="pre-commit"
        echo -e "${GREEN}✓ Found pre-commit framework${NC}"
    else
        METHOD="native"
        echo -e "${YELLOW}ℹ Pre-commit not found, using native hooks${NC}"
    fi
    echo ""
fi

# ============================================================================
# Native Git Hooks Installation
# ============================================================================

install_native_hooks() {
    echo -e "${BLUE}📦 Installing native git hooks...${NC}"
    echo ""

    # Check for jq dependency
    if ! command -v jq &> /dev/null; then
        echo -e "${RED}❌ Error: jq is required but not installed${NC}"
        echo ""
        echo "Install jq first:"
        echo "  brew install jq       # macOS"
        echo "  apt install jq        # Ubuntu/Debian"
        echo "  dnf install jq        # Fedora/RHEL"
        echo ""
        exit 1
    fi

    # Ensure validation scripts are executable
    echo -e "${BLUE}Checking script permissions...${NC}"
    chmod +x "$PROJECT_ROOT/scripts/validate-templates.sh" 2>/dev/null || true
    chmod +x "$PROJECT_ROOT/scripts/generate-manifest.sh" 2>/dev/null || true
    echo -e "${GREEN}✓ Script permissions verified${NC}"
    echo ""

    HOOK_FILE="$HOOKS_DIR/pre-commit"

    # Create hooks directory if needed
    mkdir -p "$HOOKS_DIR"

    # Write pre-commit hook
    cat > "$HOOK_FILE" << 'HOOK_EOF'
#!/bin/bash
# =============================================================================
# Claude Kit - Pre-commit Hook (Native)
# =============================================================================
#
# This hook validates templates and checks manifest integrity before commit.
# Generated by: scripts/setup-hooks.sh
#
# =============================================================================

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

PROJECT_ROOT="$(git rev-parse --show-toplevel)"

# ============================================================================
# Check if template/ modified
# ============================================================================

if ! git diff --cached --name-only | grep -q '^template/'; then
    # No template changes, skip validation
    exit 0
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 Pre-commit: Validating Templates"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ============================================================================
# Step 1: Template Validation
# ============================================================================

echo -e "${BLUE}[1/3] Running template validation...${NC}"

if ! "$PROJECT_ROOT/scripts/validate-templates.sh"; then
    echo ""
    echo -e "${RED}❌ COMMIT BLOCKED: Template validation failed${NC}"
    echo ""
    echo "Fix the errors above and try again."
    echo ""
    exit 1
fi

echo -e "${GREEN}✓ Template validation passed${NC}"
echo ""

# ============================================================================
# Step 2: Manifest Integrity Check
# ============================================================================

echo -e "${BLUE}[2/3] Checking manifest integrity...${NC}"

# Generate fresh manifest to temp file (don't modify original)
TEMP_MANIFEST=$(mktemp)
trap 'rm -f "$TEMP_MANIFEST"' EXIT

cd "$PROJECT_ROOT"
./scripts/generate-manifest.sh "$TEMP_MANIFEST" > /dev/null 2>&1

# Extract hashes
FRESH_HASH=$(jq -r '.manifest_hash // ""' "$TEMP_MANIFEST")
CURRENT_HASH=$(jq -r '.manifest_hash // ""' "$PROJECT_ROOT/template/.claude-kit-manifest.json")

# Compare hashes
if [ "$CURRENT_HASH" != "$FRESH_HASH" ]; then
    echo ""
    echo -e "${RED}❌ COMMIT BLOCKED: Manifest out of sync${NC}"
    echo ""
    echo "The manifest hash does not match your template files."
    echo "This means you modified templates but didn't regenerate the manifest."
    echo ""
    echo "To fix:"
    echo "  1. Run: ./scripts/generate-manifest.sh"
    echo "  2. Review: git diff template/.claude-kit-manifest.json"
    echo "  3. Stage: git add template/.claude-kit-manifest.json"
    echo "  4. Retry: git commit"
    echo ""
    exit 1
fi

echo -e "${GREEN}✓ Manifest integrity verified${NC}"
echo ""

# ============================================================================
# Step 3: Version Bump Check (Warning Only)
# ============================================================================

echo -e "${BLUE}[3/3] Checking version updates...${NC}"

# Get modified template files (excluding manifest and _TEMPLATE)
MODIFIED_TEMPLATES=$(git diff --cached --name-only | \
    grep '^template/' | \
    grep -v '.claude-kit-manifest.json' | \
    grep -v '_TEMPLATE' || true)

if [ -n "$MODIFIED_TEMPLATES" ]; then
    # Check if manifest was also modified (version might have been bumped)
    if ! git diff --cached --name-only | grep -q '.claude-kit-manifest.json'; then
        echo ""
        echo -e "${YELLOW}⚠️  WARNING: Template modified but manifest not staged${NC}"
        echo ""
        echo "You modified template files but didn't update the manifest."
        echo "Consider bumping the version if this is a functional change."
        echo ""
        echo "Modified files:"
        echo "$MODIFIED_TEMPLATES" | sed 's/^/  - /'
        echo ""
        echo "To bump version:"
        echo "  1. Edit version in template/.claude-kit-manifest.json"
        echo "  2. Run: ./scripts/generate-manifest.sh"
        echo "  3. Stage: git add template/.claude-kit-manifest.json"
        echo ""
        echo -e "${YELLOW}ℹ This is a warning only - commit will proceed${NC}"
        echo ""
    else
        echo -e "${GREEN}✓ Manifest updated${NC}"
        echo ""
    fi
else
    echo -e "${GREEN}✓ No version check needed${NC}"
    echo ""
fi

# ============================================================================
# Success
# ============================================================================

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✅ All pre-commit checks passed!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

exit 0
HOOK_EOF

    chmod +x "$HOOK_FILE"

    echo -e "${GREEN}✓ Pre-commit hook installed${NC}"
    echo -e "  Location: ${CYAN}$HOOK_FILE${NC}"
    echo ""
}

# ============================================================================
# Pre-commit Framework Installation
# ============================================================================

install_precommit_framework() {
    echo -e "${BLUE}📦 Setting up pre-commit framework...${NC}"
    echo ""

    # Check if pre-commit is installed
    if ! command -v pre-commit &> /dev/null; then
        echo -e "${RED}❌ Error: pre-commit not installed${NC}"
        echo ""
        echo "Install pre-commit first:"
        echo "  pip install pre-commit"
        echo "  # or"
        echo "  brew install pre-commit"
        echo ""
        echo "Or use native hooks instead:"
        echo "  ./scripts/setup-hooks.sh native"
        echo ""
        exit 1
    fi

    # Create .pre-commit-config.yaml if it doesn't exist
    if [ ! -f "$PROJECT_ROOT/.pre-commit-config.yaml" ]; then
        echo -e "${BLUE}Creating .pre-commit-config.yaml...${NC}"
        cat > "$PROJECT_ROOT/.pre-commit-config.yaml" << 'YAML_EOF'
# Claude Kit - Pre-commit Configuration
# See https://pre-commit.com for more information

repos:
  - repo: local
    hooks:
      # Template validation
      - id: validate-templates
        name: Validate Claude Kit Templates
        entry: ./scripts/validate-templates.sh
        language: system
        pass_filenames: false
        files: ^template/
        stages: [commit]

      # Manifest integrity check
      - id: check-manifest-integrity
        name: Check Manifest Integrity
        entry: bash -c '
          TEMP_MANIFEST=$(mktemp);
          trap "rm -f $TEMP_MANIFEST" EXIT;
          ./scripts/generate-manifest.sh "$TEMP_MANIFEST" > /dev/null 2>&1;
          FRESH_HASH=$(jq -r ".manifest_hash // \"\"" "$TEMP_MANIFEST");
          CURRENT_HASH=$(jq -r ".manifest_hash // \"\"" template/.claude-kit-manifest.json);
          if [ "$CURRENT_HASH" != "$FRESH_HASH" ]; then
            echo "";
            echo "❌ ERROR: Manifest out of sync";
            echo "";
            echo "Run: ./scripts/generate-manifest.sh";
            echo "";
            exit 1;
          fi
        '
        language: system
        pass_filenames: false
        files: ^template/
        stages: [commit]
YAML_EOF
        echo -e "${GREEN}✓ Created .pre-commit-config.yaml${NC}"
    else
        echo -e "${YELLOW}ℹ .pre-commit-config.yaml already exists${NC}"
    fi

    # Install hooks
    echo ""
    echo -e "${BLUE}Installing pre-commit hooks...${NC}"
    cd "$PROJECT_ROOT"
    pre-commit install

    echo ""
    echo -e "${GREEN}✓ Pre-commit framework configured${NC}"
    echo ""
}

# ============================================================================
# Main Execution
# ============================================================================

case "$METHOD" in
    native)
        install_native_hooks
        ;;
    pre-commit)
        install_precommit_framework
        ;;
    *)
        echo -e "${RED}❌ Unknown method: $METHOD${NC}"
        echo ""
        show_help
        exit 1
        ;;
esac

# ============================================================================
# Summary
# ============================================================================

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                  ✅ Hooks Installed!                         ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo -e "Method: ${CYAN}$METHOD${NC}"
echo ""
echo "Your commits will now be validated automatically for:"
echo "  ✓ Template errors (SKILL.md frontmatter)"
echo "  ✓ Manifest integrity (hash verification)"
echo "  ✓ Version updates (warning only)"
echo ""
echo "To bypass hooks (not recommended):"
echo "  git commit --no-verify"
echo ""
echo "To uninstall:"
if [ "$METHOD" == "native" ]; then
    echo "  rm $HOOKS_DIR/pre-commit"
else
    echo "  pre-commit uninstall"
fi
echo ""
