#!/bin/bash
# =============================================================================
# Claude Kit - Git Hooks Setup
# =============================================================================
#
# Installs pre-commit hooks for template validation.
#
# Usage:
#   ./scripts/setup-hooks.sh [METHOD]
#
# METHODS:
#   native        Native git hooks (no dependencies)
#   pre-commit    Pre-commit framework (requires: pip install pre-commit)
#   auto          Auto-detect (default)
#
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOKS_DIR="$PROJECT_ROOT/.git/hooks"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

# ============================================================================
# Configuration
# ============================================================================

METHOD="${1:-auto}"

show_help() {
    cat << EOF
Claude Kit - Git Hooks Setup

Installs pre-commit hooks for automated template validation.

Usage: $0 [METHOD]

METHODS:
  native        Native git hooks (no dependencies, lightweight)
  pre-commit    Pre-commit framework (industry standard, requires Python)
  auto          Auto-detect best method (default)

FEATURES:
  - Template validation (ERROR -> block commit)

EXAMPLES:
  $0              # Auto-detect
  $0 native       # Use native hooks
  $0 pre-commit   # Use pre-commit framework

EOF
}

if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]; then
    show_help
    exit 0
fi

# ============================================================================
# Pre-flight Checks
# ============================================================================

if [ ! -d "$PROJECT_ROOT/.git" ]; then
    echo -e "${RED}Error: Not a git repository${NC}"
    echo "Run this script from the claude-kit project root"
    exit 1
fi

echo ""
echo "Claude Kit - Git Hooks Setup"
echo ""

# ============================================================================
# Method Selection
# ============================================================================

if [ "$METHOD" == "auto" ]; then
    echo -e "${BLUE}Auto-detecting best method...${NC}"

    if command -v pre-commit &> /dev/null; then
        METHOD="pre-commit"
        echo -e "${GREEN}Found pre-commit framework${NC}"
    else
        METHOD="native"
        echo -e "${YELLOW}Pre-commit not found, using native hooks${NC}"
    fi
    echo ""
fi

# ============================================================================
# Native Git Hooks Installation
# ============================================================================

install_native_hooks() {
    echo -e "${BLUE}Installing native git hooks...${NC}"
    echo ""

    # Ensure validation scripts are executable
    chmod +x "$PROJECT_ROOT/scripts/validate-templates.sh" 2>/dev/null || true
    echo -e "${GREEN}Script permissions verified${NC}"
    echo ""

    HOOK_FILE="$HOOKS_DIR/pre-commit"

    # Create hooks directory if needed
    mkdir -p "$HOOKS_DIR"

    # Write pre-commit hook
    cat > "$HOOK_FILE" << 'HOOK_EOF'
#!/bin/bash
# =============================================================================
# Claude Kit - Pre-commit Hook (Native)
# =============================================================================
#
# This hook validates templates before commit.
# Generated by: scripts/setup-hooks.sh
#
# =============================================================================

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

PROJECT_ROOT="$(git rev-parse --show-toplevel)"

# ============================================================================
# Check if skills/ or agents/ modified
# ============================================================================

if ! git diff --cached --name-only | grep -qE '^(skills|agents)/'; then
    # No skills/agents changes, skip validation
    exit 0
fi

echo ""
echo "Pre-commit: Validating Templates"
echo ""

# ============================================================================
# Template Validation
# ============================================================================

echo -e "${BLUE}Running template validation...${NC}"

if ! "$PROJECT_ROOT/scripts/validate-templates.sh"; then
    echo ""
    echo -e "${RED}COMMIT BLOCKED: Template validation failed${NC}"
    echo ""
    echo "Fix the errors above and try again."
    echo ""
    exit 1
fi

echo -e "${GREEN}Template validation passed${NC}"
echo ""

exit 0
HOOK_EOF

    chmod +x "$HOOK_FILE"

    echo -e "${GREEN}Pre-commit hook installed${NC}"
    echo -e "  Location: ${CYAN}$HOOK_FILE${NC}"
    echo ""
}

# ============================================================================
# Pre-commit Framework Installation
# ============================================================================

install_precommit_framework() {
    echo -e "${BLUE}Setting up pre-commit framework...${NC}"
    echo ""

    # Check if pre-commit is installed
    if ! command -v pre-commit &> /dev/null; then
        echo -e "${RED}Error: pre-commit not installed${NC}"
        echo ""
        echo "Install pre-commit first:"
        echo "  pip install pre-commit"
        echo "  # or"
        echo "  brew install pre-commit"
        echo ""
        echo "Or use native hooks instead:"
        echo "  ./scripts/setup-hooks.sh native"
        echo ""
        exit 1
    fi

    # Create .pre-commit-config.yaml if it doesn't exist
    if [ ! -f "$PROJECT_ROOT/.pre-commit-config.yaml" ]; then
        echo -e "${BLUE}Creating .pre-commit-config.yaml...${NC}"
        cat > "$PROJECT_ROOT/.pre-commit-config.yaml" << 'YAML_EOF'
# Claude Kit - Pre-commit Configuration
# See https://pre-commit.com for more information

repos:
  - repo: local
    hooks:
      # Template validation
      - id: validate-templates
        name: Validate Claude Kit Templates
        entry: ./scripts/validate-templates.sh
        language: system
        pass_filenames: false
        files: ^(skills|agents)/
        stages: [commit]
YAML_EOF
        echo -e "${GREEN}Created .pre-commit-config.yaml${NC}"
    else
        echo -e "${YELLOW}.pre-commit-config.yaml already exists${NC}"
    fi

    # Install hooks
    echo ""
    echo -e "${BLUE}Installing pre-commit hooks...${NC}"
    cd "$PROJECT_ROOT"
    pre-commit install

    echo ""
    echo -e "${GREEN}Pre-commit framework configured${NC}"
    echo ""
}

# ============================================================================
# Main Execution
# ============================================================================

case "$METHOD" in
    native)
        install_native_hooks
        ;;
    pre-commit)
        install_precommit_framework
        ;;
    *)
        echo -e "${RED}Unknown method: $METHOD${NC}"
        echo ""
        show_help
        exit 1
        ;;
esac

# ============================================================================
# Summary
# ============================================================================

echo "Hooks Installed!"
echo ""
echo -e "Method: ${CYAN}$METHOD${NC}"
echo ""
echo "Your commits will now be validated automatically for:"
echo "  - Template errors (SKILL.md frontmatter)"
echo ""
echo "To bypass hooks (not recommended):"
echo "  git commit --no-verify"
echo ""
echo "To uninstall:"
if [ "$METHOD" == "native" ]; then
    echo "  rm $HOOKS_DIR/pre-commit"
else
    echo "  pre-commit uninstall"
fi
echo ""
